alias bazel="bazelisk"
alias c="code ."
alias dce="devcontainer exec --workspace-folder . --config"
alias dcu="devcontainer up --workspace-folder . --dotfiles-repository https://github.com/hayato-m126/dotfiles --dotfiles-target-path ~/.dotfiles --dotfiles-install-command install.sh --config"
alias g="git"
alias gb="git branch"
alias gdb="git branch | xargs git branch -D"
alias gds="git submodule deinit -f -all"
alias gf="git fetch --all --prune"
alias ghp="gh pr create --head"
alias gl="git log --oneline --graph --decorate --all"
alias gn="git switch -c"
alias gp="git pull"
alias grs="git reset --soft HEAD~"
alias gs="git switch"
alias gsd="git submodule deinit -f --all"
alias gsi="git submodule update --init --recursive"
alias jd="jj desc -m"
alias jgp="jj git push -b"
alias p="pre-commit run -a"
alias untaz="tar -I zstd -xvf"

# wsl only
if [[ -d /run/WSL ]]; then
  alias docker="wslc.exe"
fi
